### ISSUE TITLE
Interest in using swagger codegen'd API bindings?

### ISSUE THREAD

**Issue by decentral1se** [anned20/kicli#2]
Have managed to get bindings generated, would save you some work on defining payloads, I imagine:

> https://github.com/decentral1se/go-kimai

Probably needs some cleaning up and testing but I've been able to run some queries with it.

**Comment by anned20** [comment]
Looks good, but it does introduce _a lot_ of boilerplate code. I'm not sure if that's something that I would want to be included. When I get time I'll check it out and if I'm convinced I'll integrate it.
